<?php

# language dependent text used in the interface for users (not admin)
# Czech translation by Ota Lunak ota@lunak.info
# alternative coding iso-8859-2
# V. 27.02.07 /PHPlist 2.10.4

$strCharSet             = 'Windows-1250';
$strName                = 'Jméno';
$strAddress             = 'Adresa';
$strEmail               = 'Email';
$strTown                = 'Mìsto';
$strPostcode            = 'PSÈ';
$strSubscribeInfo       = 'Zaregistrujte se k odbìru nìkterého informaèního zpravodaje ze seznamu níže';
$strRequired            = '(Vyžadované pole)';
$strSubscribeTitle      = 'Zaregistrujte se v nìkterém info seznamu';
$strPleaseSelect        = 'Vyberte seznam, kde se chcete zaregistrovat, prosím';
$strSubmit              = 'Zaregistrovat se do vybraných info seznam&#367;';
$strNotAvailable        = 'Litujeme, ale žádný info seznam není k dispozici';
$strEnterName           = 'Zadejte Vaše jméno, prosím';
$strEnterEmail          = 'Zadejte Vaši emailovou adresu, prosím';
$strInvalidHostInEmail  = 'Vaše emailová adresa nebyla ovìøena. Zkontrolujte ji, prosím';
$strEnterList           = 'Vyberte info seznam, prosím';
$strPleaseEnter         = 'Zadejte prosím ';
$strThanks              = 'Dìkujeme za registraci!';
$strThanksX             = '[FIRST NAME]> Dìkujeme za registraci!';
$strEmailConfirmation   = 'Obratem zasíláme Vaši registraci potvrzující email.';
$strEmailFailed          = 'Litujeme, ale registraci potvrzující email se nepodaøilo odeslat. Zkuste znovu, prosím.';
$strUnsubscribeTitle    = 'Odhlášení z registrace odbìru zpravodaj&#367;.';
$strUnsubscribeDone     = 'Potvrzující email o odhlášení z odbìru zpravodajù bude obratem odeslán.';
$strBack                = 'Zpìt';
$strUnsubscribeInfo     = 'Zrušit registraci v nìkterém z info seznam&#367;';
$strContinue            = 'Pokraèovat';
$strUnsubscribeSelect   = 'Vyberte prosím seznam, ze kterého se chcete odhlásit';
$strAllLists            = 'Všechny info seznamy';
$strNoLists             = 'Žádný ze seznamù';
$strUnsubscribeRequestForReason = 'Je nám líto, že nemáte zájem o žádné informace. Pokud nám chcete pomoci zlepšit naše služby, sdìlte nám prosím dùvod Vašeho nezájmu:';
$strUnsubscribeFinalInfo = '<br/><b>Pozor</b>: potvrzením tlaèítka "Odhlásit" zrušíte odbìr informací <b>navždy</b>. Pokud snad chcete pouze zmìnit Vaši emailovou adresu nebo odebírané informace, využijte <a href="[PREFERENCESURL]">tento odkaz</a>.';

$strNoListsFound        = 'Litujeme, ale tato adresa v databázi neexistuje.';
$strResubmit            = 'Znovu potvrdit emailovou adresu';
$strUnsubscribeSubmit   = 'Zrušit registraci ve vybraných info seznamech';
$strValuesMissing       = 'Chybí následující požadované údaje';
$strConfirmInfo         = 'Dìkujeme za potvrzení odbìru zpravodajù zobrazených níže';
$strConfirmTitle        = 'Stránka potvrzení odbìru';
$strUserNotFound        = 'Uživatel nenalezen';
$strConfirmFailInfo     = 'Litujeme, ale pøi potvrzení došlo k chybì, specifikované níže';
$strPreferHTMLEmail     = 'Preferuji HTML formát';
$strPreferTextEmail     = 'Preferuji textový formát';
$strPreferredFormat      = 'Preferovaný formát emailu:';
$strText                 = 'Text';
$strHTML                = 'HTML';
$strUserAlreadyInitialised = 'Litujeme, ale vaše heslo již bylo nastaveno';
$strConfirmFailInfo     = 'Litujeme, ale váš požadavek pro potvrzení nelze realizovat. Zkontrolujte, zda odkaz, který jste obdrželi v emailu je úplný a na jedné øádce.';
$strPreferencesTitle    = 'Inovovat preference';
$strPreferencesInfo     = 'Prosím, potvrïte správnost informace kliknutím na tlaèítko "Inovace"';
$strUpdatePreferences   = 'Inovace';
$strPreferencesEmailChanged = 'Vaše emailová adresa je zmìnìna. Kliknìte na odkaz v potvrzujícím emailu, který obdržíte, a potvrïte registraci, prosím.';
$strYouAreBlacklisted = 'Vaše emailová adresa je na blokována, protože bylo požadováno zrušit zasílání emailù. <br/>
Kontaktujte administrátora tohoto webu, který na vaši žádost zasílání obnoví. ';
$strPreferencesNotificationSent = 'Obdržíte email, obsahující zmìny';
$strPreferencesUpdated = 'Dìkujeme, inovovali jsme Vaše data.';
$strClickHere          = 'Kliknìte zde';
$strThisLink           = '<-- zde';
$strToUnsubscribe      = 'Zrušit pøedplatné mùžete ';
$strToUpdate           = 'Inovovat vaše preference mùžete ';
$strSendHTML           = 'Zaslat HTML formát';
$strYes                = 'Ano';
$strNo                 = 'Ne';
$strUnsubscribe        = 'Odhlásit';
$strAllMailinglists    = 'Všechny info seznamy';
$strAttachmentIntro     = 'Tato zpráva obsahuje pøílohy, které mùžete otevøít pomocí prohlížeèe:';
$strLocation           = 'Místo';
$strFrequency           = 'Jak èasto Vám posíláme zprávy';
$strHourly             = 'Každou hodinu';
$strDaily               = 'Dennì';
$strWeekly             = 'Týdnì';
$strMonthly             = 'Mìsíènì';
$strChoosePassword      = 'Zadejte heslo, prosím';
$strConfirmPassword    = 'Potvrïte heslo, prosím';
$strEnterPassword       = 'Zadejte heslo, prosím';
$strForgotPassword     = 'Zapomenuté heslo';
$strPassword           = 'Heslo';
$strPassword2           = 'Znovu potvrdit heslo';
$strPasswordsNoMatch    = 'Hesla nesouhlasí';
$strEmailsNoMatch     = 'Emailová adresa neodpovídá';
$strInvalidPassword     = 'Chyba: neplatné heslo nebo emailová adresa';
$strPasswordSent        = 'Vaše heslo Vám bylo zasláno emailem. Obdržíte ho v nìkolika minutách.';
$strPasswordRemindSubject = 'Vaše heslo pro odbìr info mailù';
$strPasswordRemindMessage = 'Vaše heslo je ';
$strPasswordRemindInfo = 'Pro zaslání hesla emailem zadejte Vaši adresu emailu a stisknìte tlaèítko "'.$strForgotPassword.'"';
$strLogin               = 'Login';
$strLoginTitle          = 'Zadejte, prosím, Vaši emailovou adresu a heslo';
$strLoginInfo           = 'Zadejte, prosím, Vaši emailovou adresu a heslo';
$strPersonalLocationInfo = '
  <p>Tato stránka vyžaduje osobní identifikaci, kterou najdete v každém emailu, který jsme Vám zaslali.<br/>
  Pokud jste využili odkaz osobní identifikace a pøesto ètete toto hlášení, pøesvìdète se prosím, že odkaz je na jednom øádku, nezalomený.</p>
  <p>Pokud odkaz osobní identifikace  nemáte, vyžádejte si ho vložením Vaší emailové adresy níže a stisknìte tlaèítko "Pokraèovat"
  ';
$strPersonalLocationSent = '<h1>Povedlo se! V krátké dobì obdržíte email s Vaší osobní identifikací.</h1>';
$strUserExists   = '<br/>Uživatel se stejnou emailovou adresou již existuje a naše záznamy obsahují rozdílné heslo';
$strUserExistsExplanationStart = '<br/>Chcete-li získat heslo, kliknìte ';
$strUserExistsExplanationLink = 'ZDE';
$strUserExistsExplanationEnd = ' pro pøesmìrování na stránku získání osobní identifikace.';
$strForwardTitle = 'Pøeposlat zprávu nìkomu, koho znáte';
$strForwardSubtitle = 'Pøeposlat zprávu s pøedmìtem ';
$strForwardEnterEmail = 'Prosím, zadejte platnou emailovou adresu, komu chcete pøeposlat zprávu ';
$strForwardSuccessInfo ='Zpráva pøeposlána';
$strForwardFailInfo = 'Pøeposlání zprávy selhalo';
$strForwardAlreadyDone = 'Pøeposlání zprávy na zadanou adresu bylo úspìšné';
$strForwardFooter = 'Tuto zprávu Vám pøeposílá [FORWARDEDBY].
  Neznamená to automatickou registraci k odbìru info zpravodajù.
  Registrace - ';
$strForward = 'Forward';
$strFwd = 'Fwd'; # short version of forward for email subject
?>
