<?php

# language dependent text used in the interface for users (not admin)

$strCharSet             = 'ISO-8859-1';
$strName                = 'Nome';
$strAddress             = 'Endereço';
$strEmail               = 'Email';
$strTown                = 'Cidade';
$strPostcode            = 'CEP';
$strSubscribeInfo       = 'Inscreva-se em uma ou mais listas de email utilizando-se do formulário abaixo';
$strRequired            = 'campo necessário';
$strSubscribeTitle      = 'Inscreva-se em nossas listas de email';
$strPleaseSelect        = 'Por favor, escolha as listas em que você deseja cadastrar-se';
$strSubmit              = 'Inscreva-se nas listas selecionadas';
$strNotAvailable        = 'Perdão, não há listas disponíveis nesse momento';
$strEnterName           = 'Por favor, forneça seu nome';
$strEnterEmail          = 'Por favor, forneça seu email';
$strInvalidHostInEmail  = 'Perdão, não foi posivel verificar o e-mail, verifique se você digitou corretamente';
$strEnterList           = 'Por favor, escolha a lista na qual deseja inscrever-se';
$strPleaseEnter         = 'Por favor, forneça seu';
# the thanks message can contain placeholders
#$strThanks              = 'Dear [FIRST NAME], <br/>Thank you for subscribing to our lists.';
$strThanks              = 'Obrigado por inscrever-se em nossas listas.';
# the EmailConfirmation message can contain placeholders
#$strEmailConfirmation  = 'Your email [email] has been added to our system. You will be e-mailed shortly with confirmation of the lists you have subscribed to.';
$strEmailConfirmation   = 'Seu e-mail foi sumetido em nosso sistema. Você receberá uma mensagem com uma solicitação de confirmação. Favor clicar no link contido na mensagem para confirmar a sua inscrição.';
$strEmailFailed         = 'Perdão, o e-mail de solicitação de confirmação falhou. Clique no botão de "Recarregar" para tentar novamente. Se o problema persistir, é provável que voce esteja em nossa "Black List", o que significa que você não pode receber mensagens do sistema. Neste caso, favor contactar o Administrador do Sistema.';
$strUnsubscribeTitle    = 'Descadastre-se de nossas listas';
$strUnsubscribeDone     = 'Você foi descadastrado das listas que você selecionou. Em breve receberá um email de confirmação.';
$strBack                = 'Voltar';
$strUnsubscribeInfo     = 'Descadastre-se de uma de nossas listas de email';
$strContinue            = 'Continuar';
$strUnsubscribeSelect   = 'Por favor, escolha as listas das quais deseja se descadastrar';
$strAllLists            = 'Todas as listas';
$strNoLists             = 'Nenhuma delas';
$strUnsubscribeRequestForReason = 'Esperamos revê-lo novamente participando da nossa newsletter. Ajude-nos a melhorar o nosso serviço, Ficaremos gratos se você puder nos dizer porque esta se descadastrando:';
$strUnsubscribeFinalInfo = '<br/><b>Aviso</b>: Esta página é utilizada para cancelar o recebimento da nossa newsletter definitivamente. Se voce quiser alterar o seu e-mail ou quiser modificar as listas que voce recebe, <a href="[PREFERENCESURL]">atualize o seu cadastro</a>';
$strNoListsFound        = 'Perdão, você não está cadastrado em nenhuma de nossas listas com esse email';
$strResubmit            = 'Enviar email novamente';
$strUnsubscribeSubmit   = 'Descadastrar-se da lista selecionada';
$strValuesMissing       = 'As seguintes informações são necessárias';
$strConfirmInfo         = 'Obrigado por confirmar sua inscrição em nossas listas de email. Abaixo, a(s) lista(s) em que você está inscrito:';
$strConfirmTitle        = 'Página de confirmação do sistema';
$strUserNotFound        = 'Usuário não encontrado';
$strUserAlreadyInitialised = 'Perdão, sua senha já foi alterada';
$strConfirmFailInfo     = 'Perdão, sua confirmação está inválida. Favor verificar se o link enviado no e-mail esta correto.';
$strPreferHTMLEmail     = 'Prefiro receber e-mail em formato HTML';
$strPreferTextEmail     = 'Prefiro receber e-mail em formato Texto';
$strPreferredFormat      = 'Formato de e-mail preferido:';
$strText                 = 'Texto';
$strHTML                = 'HTML';
$strPreferencesTitle    = 'Atualize seu cadastro';
$strPreferencesInfo     = 'Favor confirmar se as informações abaixo estão corretas e clique no botão "Atualizar"';
$strUpdatePreferences   = 'Atualizar';
$strPreferencesEmailChanged = 'Seu e-mail foi alterado. Verifique a mensagem enviada para seu novo e-mail e clique no link para confirmar seu novo e-mail.';   
$strYouAreBlacklisted = 'Seu e-mail esta em nossa "Black List", o que significa que voce solicitou não mais receber nossa newsletter. <br />
Caso queira receber nossos e-mails novamente, solicite esta alteração ao Administrador do nosso sistema. Favor contactar-nos diretamente para voltar a receber a nossa newsletter e 
nos alteraremos o seu cadastro.';
$strPreferencesNotificationSent = 'Voce receberá um e-mail com as alterações';
$strPreferencesUpdated = 'Obrigado. Suas informações foram alteradas.';
$strClickHere          = 'Clique aqui';
$strThisLink           = 'este link';
$strToUnsubscribe      = 'Se voce deseja não receber mais a nossa newsletter, ';
$strToUpdate           = 'Para atualizar o seu cadastro ou para descadastrar, visite';
$strSendHTML           = 'Enviar HTML e-mail';
$strYes                = 'Sim';
$strNo                 = 'Não';
$strUnsubscribe        = 'Descadastrar';
$strAllMailinglists    = 'Todas newsletters';
$strAttachmentIntro     = 'Esta mensagem contem arquivos anexados que podem ser visualizados através de um browser web:';
$strLocation           = 'Localização';
$strFrequency           = 'Qual a freqüência para envio de mensagens';
$strHourly             = 'Hora em hora';
$strDaily               = 'Diário';
$strWeekly             = 'Semanal';
$strMonthly             = 'Mensal';
$strChoosePassword      = 'Escolha uma senha';
$strConfirmPassword    = 'Confirms sua senha';
$strEnterPassword       = 'Entre sua senha';
$strForgotPassword     = 'Esqueceu sua senha';
$strPassword           = 'Senha';
$strPassword2           = 'Confirme a Senha';
$strPasswordsNoMatch    = 'As senhas não conferem';
$strEmailsNoMatch     = 'Endereço de e-mail não confere';
$strInvalidPassword     = 'Erro: e-mail ou senha inválidos';
$strPasswordSent        = 'Sua senha foi enviada por e-mail. Você receberá a mensagem em poucos minutos';
$strPasswordRemindSubject = 'Sua senha para nossas newsletters';
$strPasswordRemindMessage = 'Sua senha é  ';
$strPasswordRemindInfo = 'Para receber sua senha por e-mail, favor informe seu e-mail e clique no botão "'.$strForgotPassword.'".';
$strLogin               = 'Login';
$strLoginTitle          = 'Entre seu e-mail e senha';
$strLoginInfo           = 'Esta página requer uma senha. Entre com seu e-mail e senha';
$strPersonalLocationInfo = '
  <p>Esta página requer uma identificação pessoal que pode ser encontrada em cada e-mail enviado para você.<br />
  Se voce clicou neste link e obteve este erro, certifique-se de copiar a linha inteira para o endereço no browser. 
  Algumas vezes, no e-mail, o link é quebrado em mais de uma linha.</p>
  <p>Se voce não conhece este link, você pode solicitar um e-mail com o link correto. Favor entre com seu e-mail e clique em  "Continuar"   
';
$strPersonalLocationSent = '<h3>Successo!</h3><p>Voce receberá uma mensagem com o seu localizado pessoal</p>';
$strUserExists   = '<br/>Um usuario com este e-mail já existe, e com uma senha diferente';
$strUserExistsExplanationStart = '<br/>Para obter sua senha, clique ';
$strUserExistsExplanationLink = 'aqui';
$strUserExistsExplanationEnd = ' para solicitar seu localizado pessoal';
$strForwardTitle = 'Encaminhe uma mensagem para alguem';
$strForwardSubtitle = 'Enceminhe a mensagem com o assunto ';
$strForwardEnterEmail = 'Entre um e-mail válido para encaminhar';
$strForwardSuccessInfo ='A mensagem foi encaminhada';
$strForwardFailInfo = 'Falha ao encaminhar a mensagem';
$strForwardAlreadyDone = 'Esta mensagem já foi encaminhada para este e-mail';
$strForwardFooter = 'Esta mensagem foi encaminhara para você por [FORWARDEDBY].
  Voce não foi inscrito automaticamente a esta newsletter.
  Para se inscrever a esta newsletter visite';
$strForward = 'Encaminhar';
$strFwd = 'Enc'; # short version of forward for email subject
?>
